'use strict';
// Generated by tools/fit-persistence.mjs from 199 archived games. Do not edit.
//
// P(a cell occupied now is still occupied at round end), indexed by turns
// remaining: <=8, <=20, <=40, then above 40.
// A foreign cell is a bet, and the odds move through a round: early the unit is
// passing through, late it has settled. Blush narrows it further, because within
// one game a colour belongs to one opponent.

const TABLE = {
  "generatedFrom": {
    "games": 199,
    "rounds": 3092,
    "minSamples": 400
  },
  "bounds": [
    8,
    20,
    40
  ],
  "modes": {
    "arena": {
      "fallback": [
        0.9619,
        0.9269,
        0.7812,
        0.4278
      ],
      "colours": {
        "#f43f5e": [
          0.9619,
          0.9467,
          0.8864,
          0.5017
        ],
        "#2563eb": [
          0.9567,
          0.9542,
          0.9353,
          0.7065
        ],
        "#facc15": [
          0.9799,
          0.9695,
          0.9287,
          0.5327
        ],
        "#ff0000": [
          0.9844,
          0.9782,
          0.9489,
          0.5519
        ],
        "#7c3aed": [
          0.9606,
          0.8075,
          0.4364,
          0.0987
        ],
        "#60a5fa": [
          null,
          null,
          0.2013,
          0.1373
        ],
        "#dc2626": [
          0.0857,
          0.0638,
          0.0364,
          null
        ],
        "#ff33cc": [
          0.9506,
          0.881,
          0.6371,
          0.2311
        ],
        "#0b5d1e": [
          0.9853,
          0.9441,
          0.7704,
          0.3923
        ],
        "#ff8c00": [
          0.9752,
          0.9695,
          0.9308,
          0.5235
        ]
      }
    },
    "clash": {
      "fallback": [
        0.9186,
        0.8305,
        0.68,
        0.2624
      ],
      "colours": {
        "#ff0000": [
          0.9224,
          0.8851,
          0.7433,
          0.3389
        ],
        "#0b5d1e": [
          0.985,
          0.9512,
          0.9117,
          0.7603
        ],
        "#2563eb": [
          0.8904,
          0.8836,
          0.8516,
          0.8168
        ]
      }
    }
  }
};

const bucketFor = turnsLeft => {
  for (let index = 0; index < TABLE.bounds.length; index++) {
    if (turnsLeft <= TABLE.bounds[index]) return index;
  }
  return TABLE.bounds.length;
};

/**
 * Probability a foreign cell of this colour is still there at round end. Falls
 * back through the mode's own default, then Arena's, which is the better
 * measured of the two.
 */
function persistence(blush, turnsLeft, mode = 'arena', fallback = 0.8) {
  const bucket = bucketFor(turnsLeft);
  const table = TABLE.modes[mode] ?? TABLE.modes.arena;
  const series = (blush && table.colours[blush]) || table.fallback;
  return series?.[bucket] ?? table.fallback?.[bucket]
    ?? TABLE.modes.arena.fallback?.[bucket] ?? fallback;
}

module.exports = { persistence, TABLE };
