'use strict';
// Generated by tools/fit-persistence.mjs from 164 archived games. Do not edit.
//
// P(a cell occupied now is still occupied at round end), indexed by turns
// remaining: <=8, <=20, <=40, then above 40.
// A foreign cell is a bet, and the odds move through a round: early the unit is
// passing through, late it has settled. Blush narrows it further, because within
// one game a colour belongs to one opponent.

const TABLE = {
  "generatedFrom": {
    "games": 164,
    "rounds": 2532,
    "minSamples": 400
  },
  "bounds": [
    8,
    20,
    40
  ],
  "fallback": [
    0.961,
    0.9233,
    0.7614,
    0.4199
  ],
  "colours": {
    "#f43f5e": [
      0.9619,
      0.9467,
      0.8864,
      0.5017
    ],
    "#2563eb": [
      0.955,
      0.9521,
      0.9309,
      0.6812
    ],
    "#facc15": [
      0.9799,
      0.9695,
      0.9287,
      0.5327
    ],
    "#ff0000": [
      0.9903,
      0.9809,
      0.9385,
      0.5429
    ],
    "#7c3aed": [
      null,
      0.7611,
      0.4218,
      0.1055
    ],
    "#60a5fa": [
      null,
      null,
      0.2091,
      0.1344
    ],
    "#dc2626": [
      0.1098,
      0.0888,
      0.0547,
      null
    ],
    "#ff33cc": [
      0.9506,
      0.881,
      0.6371,
      0.2311
    ],
    "#0b5d1e": [
      0.9838,
      0.9393,
      0.7374,
      0.3307
    ],
    "#ff8c00": [
      0.9752,
      0.9695,
      0.9308,
      0.5235
    ]
  }
};

const bucketFor = turnsLeft => {
  for (let index = 0; index < TABLE.bounds.length; index++) {
    if (turnsLeft <= TABLE.bounds[index]) return index;
  }
  return TABLE.bounds.length;
};

/** Probability a foreign cell of this colour is still there at round end. */
function persistence(blush, turnsLeft, fallback = 0.8) {
  const bucket = bucketFor(turnsLeft);
  const series = (blush && TABLE.colours[blush]) || TABLE.fallback;
  return series?.[bucket] ?? TABLE.fallback?.[bucket] ?? fallback;
}

module.exports = { persistence, TABLE };
